services:
  vitepress:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    command: npm run docs:dev -- --host 0.0.0.0
    tty: true
    stdin_open: true
